version: '3'

services:
  db:
    env_file:
      - .env
    container_name: postgreslocal
    image: postgres:16-alpine3.19
    volumes:
      - ${LOCAL_PATH_POSTGRES_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  
  pgadmin:
    depends_on:
      - db
    
    env_file:
      - .env
    image: dpage/pgadmin4
    volumes:
      - ${LOCAL_PATH_PG_ADMIN_VOLUME}:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80